version: '3.0'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "xxx"
      POSTGRES_PASSWORD: "xxx"
      POSTGRES_DB: "xxx"
volumes:
  postgres-volume: